### ISSUE TITLE
Node 7/8 for Async & Await

### ISSUE THREAD

**Issue by DenisCarriere** [YOWCT/pothole_webserver#2]
Since this web server is a backend application and using Docker you can use any Node version, you should build it with one of the latest versions of Node to have `async` & `await` support and all the bells & whistle of ES6 instead of the LTS version (Node 6).

Switching back and forth between NodeJS version is pretty easy using [`nvm`](https://github.com/creationix/nvm).

```bash
$ nvm install 7
$ nvm use 7
$ nvm use 8
```

**Comment by devisscher** [comment]
Switched to node:8. Is nvm necessary to run the container or is it just for local dev? @DenisCarriere

**Comment by DenisCarriere** [comment]
Nvm is only for local dev purposes, the recent Dockerfile simply just needs to use the recent node image.

We could also specify the `engine` version in the package.json
